services:
  web:
    build: .
    container_name: iota
    ports:
      - 8080:8080
    environment:
      - TELEMETRY_LOGGING_INTERVAL_READ=60
      - TELEMETRY_LOGGING_INTERVAL_WRITE=300
      - TELEMETRY_REPORTING_INTERVAL_WRITE=600
      - TELEMETRY_REPORTING_THRESHOLD_TEMPERATURE=45
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=telemetry
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 10